export enum ErrorType {
  INVALID_KEY = 'invalid_key',
  INVALID_LICENCE = 'invalid_licence',
  INVALID_LICENCE_TYPE = 'invalid_licence_type',
  LICENSE_EXPIRED = 'license_expired',
  INVALID_LICENCE_CREATED_AT = 'invalid_licence_created_at',
  WEBSITE_NOT_FOUND = 'website_not_found',
  WEBSITE_NOT_FOUND_BY_LICENCE = 'website_not_found_by_licence',
  WEBSITE_ALREADY_EXISTS = 'website_already_exists',
  USER_NOT_FOUND = 'user_not_found',
  UNAUTHORIZED = 'unauthorized',
  INVALID_PASSWORD = 'invalid_password',
  USER_ALREADY_EXISTS = 'user_already_exists',
  INTERNAL_SERVER_ERROR = 'internal_server_error',
  WEBHOOK_URL_INVALID = 'webhook_url_invalid',
  ROLE_NOT_FOUND = 'role_not_found',
  ROLE_NOT_MODIFIABLE = 'role_not_modifiable',
  ROLE_ALREADY_EXISTS = 'role_already_exists',
  ROLE_UPDATE_FAILED = 'role_update_failed',
  SERVER_NOT_FOUND = 'server_not_found',
  SERVER_UPDATE_FAILED = 'server_update_failed',
  SERVER_CONNECTION_FAILED = 'server_connection_failed',
  PRODUCT_NOT_FOUND = 'product_not_found',
  PRODUCT_UPDATE_FAILED = 'product_update_failed',
  PRODUCT_DELETE_FAILED = 'product_delete_failed',
  CATEGORY_NOT_FOUND = 'category_not_found',
  CATEGORY_UPDATE_FAILED = 'category_update_failed',
  CATEGORY_DELETE_FAILED = 'category_delete_failed',
  CATEGORY_HAS_PRODUCTS = 'category_has_products',
  ROLE_HAS_USERS = 'role_has_users',
  SERVER_HAS_PRODUCTS = 'server_has_products',
  INVALID_REFRESH_TOKEN = 'invalid_refresh_token',
  INVALID_ACCESS_TOKEN = 'invalid_access_token',
  INSUFFICIENT_BALANCE = 'insufficient_balance',
  CHEST_ITEM_NOT_FOUND = 'chest_item_not_found',
  CHEST_ITEM_ALREADY_USED = 'chest_item_already_used',
  CHEST_ITEM_CANNOT_GIFT_TO_SELF = 'chest_item_cannot_gift_to_self',
  TARGET_USER_NOT_FOUND = 'target_user_not_found',
  PAYMENT_PROVIDER_NOT_FOUND = 'payment_provider_not_found',
  PAYMENT_NOT_FOUND = 'payment_not_found',
  CANNOT_DELETE_DEFAULT_ROLE = 'cannot_delete_default_role',
  INSUFFICIENT_PERMISSION = "insufficient_permission",
  SLIDER_NOT_FOUND = "slider_not_found",
  INVALID_OPERATION = "invalid_operation",
  INVALID_AMOUNT = "invalid_amount",
  REPORT_NOT_FOUND = "report_not_found",
  WARNING_NOT_FOUND = "warning_not_found",
  WALL_MESSAGE_NOT_FOUND = "wall_message_not_found",
  WALL_REPLY_NOT_FOUND = "wall_reply_not_found",
  PRODUCT_BULK_DISCOUNT_FAILED = 'product_bulk_discount_failed',
  PRODUCT_DISCOUNT_FAILED = 'product_discount_failed',
  INVALID_PRODUCT_STOCK = 'invalid_product_stock',
  COUPON_NOT_FOUND = 'coupon_not_found',
  COUPON_ALREADY_EXISTS = 'coupon_already_exists',
  COUPON_INACTIVE = 'coupon_inactive',
  COUPON_USAGE_LIMIT_REACHED = 'coupon_usage_limit_reached',
  COUPON_NOT_ASSIGNED_TO_USER = 'coupon_not_assigned_to_user',
  COUPON_ALREADY_USED_BY_USER = 'coupon_already_used_by_user',
  COUPON_CART_TOTAL_BELOW_MINIMUM = 'coupon_cart_total_below_minimum',
  COUPON_INVALID_FOR_PRODUCT = 'coupon_invalid_for_product',
  COUPON_INVALID_TYPE = 'coupon_invalid_type',
  COUPON_UPDATE_FAILED = 'coupon_update_failed',
  COUPON_DELETE_FAILED = 'coupon_delete_failed',
  POST_NOT_FOUND = 'post_not_found',
  POST_FEATURED_IMAGE_UPLOAD_ERROR = 'post_featured_image_upload_error',
  TICKET_NOT_FOUND = 'ticket_not_found',
  TICKET_CATEGORY_NOT_FOUND = 'ticket_category_not_found',
  TICKET_CATEGORY_ALREADY_EXISTS = 'ticket_category_already_exists',
  TICKET_CATEGORY_HAS_TICKETS = 'ticket_category_has_tickets',
  TICKET_ALREADY_CLOSED = 'ticket_already_closed',
  TICKET_UPDATE_FAILED = 'ticket_update_failed',
  TICKET_DELETE_FAILED = 'ticket_delete_failed',
  TICKET_CATEGORY_UPDATE_FAILED = 'ticket_category_update_failed',
  TICKET_CATEGORY_DELETE_FAILED = 'ticket_category_delete_failed',
  TICKET_MESSAGE_TEMPLATE_NOT_FOUND = 'ticket_message_template_not_found',
  TICKET_MESSAGE_TEMPLATE_ALREADY_EXISTS = 'ticket_message_template_already_exists',
  TICKET_MESSAGE_TEMPLATE_NOT_ACTIVE = 'ticket_message_template_not_active',
  TICKET_MESSAGE_TEMPLATE_UPDATE_FAILED = 'ticket_message_template_update_failed',
  TICKET_MESSAGE_TEMPLATE_DELETE_FAILED = 'ticket_message_template_delete_failed',
  ITEM_NOT_FOUND = 'item_not_found',
  ITEM_ALREADY_EXISTS = 'item_already_exists',
  FAQ_NOT_FOUND = 'faq_not_found',
  FAQ_ALREADY_EXISTS = 'faq_already_exists',
  CATEGORY_ALREADY_EXISTS = 'category_already_exists',
  CATEGORY_HAS_ITEMS = 'category_has_items',
  INSUFFICIENT_PERMISSIONS = 'insufficient_permissions',
  CANNOT_UPDATE_PERMISSIONS_OF_NON_MODIFIABLE_ROLE = 'cannot_update_permissions_of_non_modifiable_role',
  CANNOT_REMOVE_PERMISSIONS_FROM_OWNER_ROLE = 'cannot_remove_permissions_from_owner_role',
  CANNOT_DELETE_DEFAULT_ROLE_WITHOUT_NEW_DEFAULT = 'cannot_delete_default_role_without_new_default',
  IP_REGISTRATION_LIMIT_EXCEEDED = 'ip_registration_limit_exceeded',
  AUTHME_CONNECTION_FAILED = 'authme_connection_failed',
  REGISTRATION_CLOSED = 'registration_closed',
  INVALID_LICENSE_DOMAIN = 'invalid_license_domain',
  LICENSE_DEACTIVE = 'license_deactive',
  LICENSE_PENDING = 'license_pending',
  LICENSE_PERMANENTLY_BANNED = 'license_permanently_banned',
  LICENSE_WAIT_FOR_PAYMENT = 'license_wait_for_payment',
  LICENSE_WAIT_FOR_APPROVE = 'license_wait_for_approve',
  TURNSTILE_TOKEN_MISSING = 'turnstile_token_missing',
  TURNSTILE_FAILED = 'turnstile_failed',
  SECURITY_CONFIG_NOT_FOUND = 'security_config_not_found',
  REDEEM_CODE_NOT_FOUND = 'redeem_code_not_found',
  REDEEM_CODE_ALREADY_EXISTS = 'redeem_code_already_exists',
  REDEEM_CODE_INACTIVE = 'redeem_code_inactive',
  REDEEM_CODE_USAGE_LIMIT_REACHED = 'redeem_code_usage_limit_reached',
  REDEEM_CODE_NOT_ASSIGNED_TO_USER = 'redeem_code_not_assigned_to_user',
  REDEEM_CODE_ALREADY_USED_BY_USER = 'redeem_code_already_used_by_user',
  REDEEM_CODE_INVALID_TYPE = 'redeem_code_invalid_type',
  REDEEM_CODE_UPDATE_FAILED = 'redeem_code_update_failed',
  REDEEM_CODE_DELETE_FAILED = 'redeem_code_delete_failed',
  REDEEM_CODE_INVALID_REWARD = 'redeem_code_invalid_reward',
  INVALID_EMAIL_ADDRESS = 'invalid_email_address',
  EMAIL_UPDATE_REQUIRED = 'email_update_required',
  PAGE_NOT_FOUND = 'page_not_found',
  PAGE_ALREADY_EXISTS = 'page_already_exists',
  PAGE_SLUG_ALREADY_EXISTS = 'page_slug_already_exists',
  PAGE_UPDATE_FAILED = 'page_update_failed',
  PAGE_DELETE_FAILED = 'page_delete_failed',
  PAGE_PUBLISH_FAILED = 'page_publish_failed',
  PAGE_VERSION_NOT_FOUND = 'page_version_not_found',
  PAGE_IS_SYSTEM_PAGE = 'page_is_system_page',
  ALREADY_EXISTS = 'already_exists',
  NOT_FOUND = 'not_found',
  FORBIDDEN = 'forbidden',
  ADDON_IN_USE = 'addon_in_use',
  FEATURE_IN_USE = 'feature_in_use',
  INVALID_ADDON_STRUCTURE = 'invalid_addon_structure',
  INVALID_ADDON_ID = 'invalid_addon_id',
  INVALID_FEATURE_ID = 'invalid_feature_id',
  CATEGORY_MISSING_ADDONS = 'category_missing_addons',
  SELECTED_ADDONS_REQUIRED = 'selected_addons_required'
}

export const ErrorMessages = {
  [ErrorType.INVALID_KEY]: "Geçersiz anahtar. Lütfen doğru bir anahtar kullandığınızdan emin olun.",
  [ErrorType.INVALID_LICENCE]: "Geçersiz lisans. Lütfen lisans bilgilerinizi kontrol edin.",
  [ErrorType.INVALID_LICENCE_TYPE]: "Geçersiz lisans türü. Desteklenen bir lisans türü giriniz.",
  [ErrorType.LICENSE_EXPIRED]: "Lisans süresi dolmuş. Lütfen lisansınızı yenileyin.",
  [ErrorType.INVALID_LICENCE_CREATED_AT]: "Lisans oluşturulma tarihi geçersiz. Lütfen sistem yöneticinizle iletişime geçin.",
  [ErrorType.WEBSITE_NOT_FOUND]: "Web sitesi bulunamadı. Lütfen geçerli bir web sitesi ID'si giriniz.",
  [ErrorType.WEBSITE_NOT_FOUND_BY_LICENCE]: "Lisans ile ilişkili web sitesi bulunamadı. Lisans bilgilerinizi kontrol edin.",
  [ErrorType.WEBSITE_ALREADY_EXISTS]: "Bu domain adresiyle kayıtlı bir website zaten mevcut.",
  [ErrorType.USER_NOT_FOUND]: "Kullanıcı bulunamadı. Lütfen kullanıcı bilgilerinizi kontrol edin.",
  [ErrorType.UNAUTHORIZED]: "Yetkisiz erişim. Bu işlemi gerçekleştirmek için yetkiniz yok.",
  [ErrorType.INVALID_PASSWORD]: "Geçersiz şifre. Lütfen şifrenizi tekrar kontrol edin.",
  [ErrorType.USER_ALREADY_EXISTS]: "Bu kullanıcı zaten mevcut. Farklı bir kullanıcı adı veya e-posta deneyin.",
  [ErrorType.INTERNAL_SERVER_ERROR]: "Sunucu hatası oluştu. Lütfen daha sonra tekrar deneyin veya destek ekibiyle iletişime geçin.",
  [ErrorType.WEBHOOK_URL_INVALID]: "Webhook URL'si geçersiz. Lütfen doğru bir URL giriniz.",
  [ErrorType.ROLE_NOT_FOUND]: "Rol bulunamadı. Lütfen geçerli bir rol seçiniz.",
  [ErrorType.ROLE_NOT_MODIFIABLE]: "Bu rol değiştirilemez. Sistem rolleri üzerinde değişiklik yapılamaz.",
  [ErrorType.ROLE_ALREADY_EXISTS]: "Bu rol zaten mevcut. Farklı bir rol adı giriniz.",
  [ErrorType.ROLE_UPDATE_FAILED]: "Rol güncellenemedi. Lütfen bilgileri kontrol edip tekrar deneyin.",
  [ErrorType.SERVER_NOT_FOUND]: "Sunucu bulunamadı. Lütfen geçerli bir sunucu ID'si giriniz.",
  [ErrorType.SERVER_UPDATE_FAILED]: "Sunucu güncellenemedi. Lütfen bilgileri kontrol edin.",
  [ErrorType.SERVER_CONNECTION_FAILED]: "Sunucuya bağlantı başarısız. Sunucu ayarlarını ve bağlantınızı kontrol edin.",
  [ErrorType.PRODUCT_NOT_FOUND]: "Ürün bulunamadı. Lütfen geçerli bir ürün ID'si giriniz.",
  [ErrorType.PRODUCT_UPDATE_FAILED]: "Ürün güncellenemedi. Lütfen ürün bilgilerini kontrol edin.",
  [ErrorType.PRODUCT_DELETE_FAILED]: "Ürün silinemedi. Lütfen daha sonra tekrar deneyin.",
  [ErrorType.CATEGORY_NOT_FOUND]: "Kategori bulunamadı. Lütfen geçerli bir kategori seçiniz.",
  [ErrorType.CATEGORY_UPDATE_FAILED]: "Kategori güncellenemedi. Lütfen kategori bilgilerini kontrol edin.",
  [ErrorType.CATEGORY_DELETE_FAILED]: "Kategori silinemedi. Lütfen daha sonra tekrar deneyin.",
  [ErrorType.CATEGORY_HAS_PRODUCTS]: "Bu kategoriye bağlı ürünler mevcut. Önce ürünleri siliniz.",
  [ErrorType.ROLE_HAS_USERS]: "Bu role atanmış kullanıcılar var. Önce kullanıcıların rollerini değiştiriniz.",
  [ErrorType.SERVER_HAS_PRODUCTS]: "Bu sunucuya bağlı ürünler mevcut. Önce ürünleri siliniz.",
  [ErrorType.INVALID_REFRESH_TOKEN]: "Yenileme anahtarı geçersiz veya süresi dolmuş. Lütfen tekrar giriş yapınız.",
  [ErrorType.INVALID_ACCESS_TOKEN]: "Erişim anahtarı geçersiz veya süresi dolmuş. Lütfen tekrar giriş yapınız.",
  [ErrorType.INSUFFICIENT_BALANCE]: "Yetersiz bakiye. Lütfen hesabınıza bakiye yükleyin.",
  [ErrorType.INSUFFICIENT_PERMISSION]: "Bu işlemi yapmak için yeterli izniniz yok. Sistem yöneticinizle iletişime geçin.",
  [ErrorType.CHEST_ITEM_NOT_FOUND]: "Sandık öğesi bulunamadı. Lütfen geçerli bir öğe seçiniz.",
  [ErrorType.CHEST_ITEM_ALREADY_USED]: "Bu sandık öğesi zaten kullanılmış. Başka bir öğe seçiniz.",
  [ErrorType.CHEST_ITEM_CANNOT_GIFT_TO_SELF]: "Kendi kendinize hediye gönderemezsiniz.",
  [ErrorType.TARGET_USER_NOT_FOUND]: "Hedef kullanıcı bulunamadı. Lütfen geçerli bir kullanıcı seçiniz.",
  [ErrorType.PAYMENT_PROVIDER_NOT_FOUND]: "Ödeme sağlayıcısı bulunamadı. Lütfen geçerli bir sağlayıcı seçiniz.",
  [ErrorType.PAYMENT_NOT_FOUND]: "Ödeme kaydı bulunamadı. Lütfen ödeme bilgilerinizi kontrol edin.",
  [ErrorType.CANNOT_DELETE_DEFAULT_ROLE]: "Varsayılan rol silinemez. Farklı bir rol seçiniz.",
  [ErrorType.SLIDER_NOT_FOUND]: "Slider bulunamadı. Lütfen geçerli bir slider seçiniz.",
  [ErrorType.INVALID_OPERATION]: "Geçersiz işlem. Lütfen yapmak istediğiniz işlemi kontrol edin.",
  [ErrorType.INVALID_AMOUNT]: "Geçersiz tutar. Lütfen geçerli bir miktar giriniz.",
  [ErrorType.REPORT_NOT_FOUND]: "Rapor bulunamadı. Lütfen geçerli bir rapor seçiniz.",
  [ErrorType.WARNING_NOT_FOUND]: "Uyarı bulunamadı. Lütfen geçerli bir uyarı seçiniz.",
  [ErrorType.WALL_MESSAGE_NOT_FOUND]: "Duvar mesajı bulunamadı. Lütfen geçerli bir duvar mesajı seçiniz.",
  [ErrorType.WALL_REPLY_NOT_FOUND]: "Duvar yanıtı bulunamadı. Lütfen geçerli bir duvar yanıtı seçiniz.",
  [ErrorType.PRODUCT_BULK_DISCOUNT_FAILED]: "Toplu ürün indirimi başarısız oldu. Lütfen ürünleri ve bilgileri kontrol edin.",
  [ErrorType.PRODUCT_DISCOUNT_FAILED]: "Ürün indirimi başarısız oldu. Lütfen ürün ve indirim bilgilerini kontrol edin.",
  [ErrorType.INVALID_PRODUCT_STOCK]: "Stok değeri -1 veya 0 ve üzeri olmalıdır.",
  [ErrorType.COUPON_NOT_FOUND]: "Kupon bulunamadı. Lütfen geçerli bir kupon seçiniz.",
  [ErrorType.COUPON_ALREADY_EXISTS]: "Bu kupon zaten mevcut. Farklı bir kupon adı giriniz.",
  [ErrorType.COUPON_INACTIVE]: "Bu kupon etkin değil. Lütfen etkin bir kupon seçiniz.",
  [ErrorType.COUPON_USAGE_LIMIT_REACHED]: "Kupon kullanım limiti ulaşıldı. Lütfen farklı bir kupon seçiniz.",
  [ErrorType.COUPON_NOT_ASSIGNED_TO_USER]: "Bu kupon bu kullanıcıya atanmamış. Lütfen kullanıcıya atanmış bir kupon seçiniz.",
  [ErrorType.COUPON_ALREADY_USED_BY_USER]: "Bu kupon bu kullanıcı tarafından zaten kullanıldı. Lütfen farklı bir kupon seçiniz.",
  [ErrorType.COUPON_CART_TOTAL_BELOW_MINIMUM]: "Sepet toplamı minimum tutarın altında. Lütfen minimum tutarı karşılayacak bir kupon seçiniz.",
  [ErrorType.COUPON_INVALID_FOR_PRODUCT]: "Bu kupon bu ürün için geçersiz. Lütfen geçerli bir kupon seçiniz.",
  [ErrorType.COUPON_INVALID_TYPE]: "Geçersiz kupon türü. Lütfen desteklenen bir kupon türü giriniz.",
  [ErrorType.COUPON_UPDATE_FAILED]: "Kupon güncellenemedi. Lütfen bilgileri kontrol edin.",
  [ErrorType.COUPON_DELETE_FAILED]: "Kupon silinemedi. Lütfen daha sonra tekrar deneyin.",
  [ErrorType.POST_NOT_FOUND]: "Post bulunamadı. Lütfen geçerli bir post ID veya slug giriniz.",
  [ErrorType.POST_FEATURED_IMAGE_UPLOAD_ERROR]: "Post öne çıkan resmi yüklenirken bir hata oluştu.",
  [ErrorType.TICKET_NOT_FOUND]: "Destek talebi bulunamadı. Lütfen geçerli bir destek talebi ID'si giriniz.",
  [ErrorType.TICKET_CATEGORY_NOT_FOUND]: "Destek talebi kategorisi bulunamadı. Lütfen geçerli bir kategori seçiniz.",
  [ErrorType.TICKET_CATEGORY_ALREADY_EXISTS]: "Bu destek talebi kategorisi zaten mevcut. Farklı bir kategori adı giriniz.",
  [ErrorType.TICKET_CATEGORY_HAS_TICKETS]: "Bu kategoriye bağlı destek talepleri mevcut. Önce destek taleplerini siliniz.",
  [ErrorType.TICKET_ALREADY_CLOSED]: "Bu destek talebi zaten kapatılmış.",
  [ErrorType.TICKET_UPDATE_FAILED]: "Destek talebi güncellenemedi. Lütfen bilgileri kontrol edin.",
  [ErrorType.TICKET_DELETE_FAILED]: "Destek talebi silinemedi. Lütfen daha sonra tekrar deneyin.",
  [ErrorType.TICKET_CATEGORY_UPDATE_FAILED]: "Destek talebi kategorisi güncellenemedi. Lütfen bilgileri kontrol edin.",
  [ErrorType.TICKET_CATEGORY_DELETE_FAILED]: "Destek talebi kategorisi silinemedi. Lütfen daha sonra tekrar deneyin.",
  [ErrorType.TICKET_MESSAGE_TEMPLATE_NOT_FOUND]: "Mesaj şablonu bulunamadı. Lütfen geçerli bir şablon ID'si giriniz.",
  [ErrorType.TICKET_MESSAGE_TEMPLATE_ALREADY_EXISTS]: "Bu mesaj şablonu zaten mevcut. Farklı bir şablon adı giriniz.",
  [ErrorType.TICKET_MESSAGE_TEMPLATE_NOT_ACTIVE]: "Bu mesaj şablonu aktif değil. Lütfen aktif bir şablon seçiniz.",
  [ErrorType.TICKET_MESSAGE_TEMPLATE_UPDATE_FAILED]: "Mesaj şablonu güncellenemedi. Lütfen bilgileri kontrol edin.",
  [ErrorType.TICKET_MESSAGE_TEMPLATE_DELETE_FAILED]: "Mesaj şablonu silinemedi. Lütfen daha sonra tekrar deneyin.",
  // Help Center Error Messages
  [ErrorType.ITEM_NOT_FOUND]: "Yardım merkezi öğesi bulunamadı. Lütfen geçerli bir öğe ID'si giriniz.",
  [ErrorType.ITEM_ALREADY_EXISTS]: "Bu yardım merkezi öğesi zaten mevcut. Farklı bir ID kullanınız.",
  [ErrorType.FAQ_NOT_FOUND]: "FAQ bulunamadı. Lütfen geçerli bir FAQ ID'si giriniz.",
  [ErrorType.FAQ_ALREADY_EXISTS]: "Bu FAQ zaten mevcut. Farklı bir ID kullanınız.",
  [ErrorType.CATEGORY_ALREADY_EXISTS]: "Bu kategori zaten mevcut. Farklı bir ID kullanınız.",
  [ErrorType.CATEGORY_HAS_ITEMS]: "Bu kategoriye bağlı öğeler mevcut. Önce öğeleri siliniz.",
  [ErrorType.INSUFFICIENT_PERMISSIONS]: "Bu işlemi yapmak için yeterli izniniz yok. Sistem yöneticinizle iletişime geçin.",
  [ErrorType.CANNOT_UPDATE_PERMISSIONS_OF_NON_MODIFIABLE_ROLE]: "Değiştirilemez rollerin izinleri güncellenemez. Sadece rol adı ve rengi değiştirilebilir.",
  [ErrorType.CANNOT_REMOVE_PERMISSIONS_FROM_OWNER_ROLE]: "Kurucu rolünden yetki eksiltilemez. Tüm yetkiler korunmalıdır.",
  [ErrorType.CANNOT_DELETE_DEFAULT_ROLE_WITHOUT_NEW_DEFAULT]: "Varsayılan rol silinemez. Önce başka bir rolü varsayılan olarak ayarlayın.",
  [ErrorType.IP_REGISTRATION_LIMIT_EXCEEDED]: "Bu IP adresinden maksimum kayıt sayısına ulaşıldı.",
  [ErrorType.AUTHME_CONNECTION_FAILED]: "AuthMe veya MySQL bağlantısı başarısız. Lütfen AuthMe ayarlarınızı ve veritabanı bağlantınızı kontrol edin.",
  [ErrorType.REGISTRATION_CLOSED]: "Kayıtlar şu anda kapalı. Yeni kullanıcı kaydı alınmamaktadır.",
  [ErrorType.INVALID_LICENSE_DOMAIN]: "İsteği oluşturduğunuz domain geçersiz.",
  [ErrorType.LICENSE_DEACTIVE]: "Lisansınız deaktive edilmiş, lütfen https://crafter.net.tr/ adresini ziyaret edin.",
  [ErrorType.LICENSE_PENDING]: "Lisansınız henüz onay bekliyor. Lütfen https://crafter.net.tr/ adresinden durumunuzu kontrol edin.",
  [ErrorType.LICENSE_PERMANENTLY_BANNED]: "Lisansınız kalıcı olarak yasaklanmış. Lütfen https://crafter.net.tr/ adresinden destek ekibiyle iletişime geçin.",
  [ErrorType.LICENSE_WAIT_FOR_PAYMENT]: "Ödeme bekleniyor. Lütfen https://crafter.net.tr/ adresinden ödemenizi tamamlayın.",
  [ErrorType.LICENSE_WAIT_FOR_APPROVE]: "Lisansınız onay bekliyor. Lütfen https://crafter.net.tr/ adresinden durumunuzu kontrol edin.",
  [ErrorType.TURNSTILE_TOKEN_MISSING]: "Cloudflare Turnstile doğrulama tokenı eksik.",
  [ErrorType.TURNSTILE_FAILED]: "Cloudflare Turnstile doğrulaması başarısız. Lütfen sayfayı yenileyip tekrar deneyin.",
  [ErrorType.SECURITY_CONFIG_NOT_FOUND]: "Güvenlik yapılandırması bulunamadı. Lütfen sistem yöneticinizle iletişime geçin.",
  [ErrorType.REDEEM_CODE_NOT_FOUND]: "Redeem kodu bulunamadı. Lütfen geçerli bir kod giriniz.",
  [ErrorType.REDEEM_CODE_INVALID_REWARD]: "Geçersiz redeem kodu ödülü. Lütfen geçerli bir ödül tanımlayınız.",
  [ErrorType.INVALID_EMAIL_ADDRESS]: "Geçersiz e-posta adresi. Lütfen geçerli bir e-posta adresi kullanınız.",
  [ErrorType.EMAIL_UPDATE_REQUIRED]: "E-posta adresiniz geçersiz. Lütfen profilinizden e-posta adresinizi güncelleyiniz.",
  [ErrorType.PAGE_NOT_FOUND]: "Sayfa bulunamadı. Lütfen geçerli bir sayfa ID'si giriniz.",
  [ErrorType.PAGE_ALREADY_EXISTS]: "Bu sayfa zaten mevcut. Farklı bir sayfa adı giriniz.",
  [ErrorType.PAGE_SLUG_ALREADY_EXISTS]: "Bu slug zaten kullanılıyor. Lütfen farklı bir slug giriniz.",
  [ErrorType.PAGE_UPDATE_FAILED]: "Sayfa güncellenemedi. Lütfen bilgileri kontrol edin.",
  [ErrorType.PAGE_DELETE_FAILED]: "Sayfa silinemedi. Lütfen daha sonra tekrar deneyin.",
  [ErrorType.PAGE_PUBLISH_FAILED]: "Sayfa yayınlanamadı. Lütfen daha sonra tekrar deneyin.",
  [ErrorType.PAGE_VERSION_NOT_FOUND]: "Sayfa versiyonu bulunamadı. Lütfen geçerli bir versiyon numarası giriniz.",
  [ErrorType.PAGE_IS_SYSTEM_PAGE]: "Sistem sayfaları düzenlenemez veya silinemez.",
  [ErrorType.ALREADY_EXISTS]: "Bu kayıt zaten mevcut.",
  [ErrorType.NOT_FOUND]: "Kayıt bulunamadı.",
  [ErrorType.FORBIDDEN]: "Bu işlemi gerçekleştirme yetkiniz yok.",
  [ErrorType.REDEEM_CODE_ALREADY_EXISTS]: "Bu redeem kodu zaten mevcut. Farklı bir kod giriniz.",
  [ErrorType.REDEEM_CODE_INACTIVE]: "Bu redeem kodu etkin değil. Lütfen etkin bir kod seçiniz.",
  [ErrorType.REDEEM_CODE_USAGE_LIMIT_REACHED]: "Redeem kodu kullanım limiti ulaşıldı. Lütfen farklı bir kod seçiniz.",
  [ErrorType.REDEEM_CODE_NOT_ASSIGNED_TO_USER]: "Bu redeem kodu bu kullanıcıya atanmamış. Lütfen kullanıcıya atanmış bir kod seçiniz.",
  [ErrorType.REDEEM_CODE_ALREADY_USED_BY_USER]: "Bu redeem kodu bu kullanıcı tarafından zaten kullanıldı. Lütfen farklı bir kod seçiniz.",
  [ErrorType.REDEEM_CODE_INVALID_TYPE]: "Geçersiz redeem kodu türü. Lütfen desteklenen bir tür giriniz.",
  [ErrorType.REDEEM_CODE_UPDATE_FAILED]: "Redeem kodu güncellenemedi. Lütfen bilgileri kontrol edin.",
  [ErrorType.REDEEM_CODE_DELETE_FAILED]: "Redeem kodu silinemedi. Lütfen daha sonra tekrar deneyin.",
  [ErrorType.ADDON_IN_USE]: "Bu addon silinemez çünkü ürünler tarafından kullanılıyor.",
  [ErrorType.FEATURE_IN_USE]: "Bu özellik silinemez çünkü ürünler tarafından kullanılıyor.",
  [ErrorType.INVALID_ADDON_STRUCTURE]: "Geçersiz addon yapısı. Lütfen addon bilgilerini kontrol edin.",
  [ErrorType.INVALID_ADDON_ID]: "Geçersiz addon ID. Bu ID kategoride bulunamadı.",
  [ErrorType.INVALID_FEATURE_ID]: "Geçersiz feature ID. Bu ID addon'da bulunamadı.",
  [ErrorType.CATEGORY_MISSING_ADDONS]: "Bu kategoride addon tanımlanmamış.",
  [ErrorType.SELECTED_ADDONS_REQUIRED]: "Bu kategori için ürün özellikleri seçilmelidir.",
};
